version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:
    medius-db:
        image: mysql:8.0
        environment:   # Set up mysql database name and password
            MYSQL_ROOT_PASSWORD: Vinbdi@2021
            MYSQL_DATABASE: dialog-generation-db
            MYSQL_USER: vinbdi
            MYSQL_PASSWORD: Vinbdi@2021
            MYSQL_ROOT_PASSWORD: Vinbdi@2021@2021
        networks:
            - medius-network
        volumes:
            - ./medius-db/mount:/var/lib/mysql
            - ./medius-db/sampledb.sql:/docker-entrypoint-initdb.d/sampledb.sql
        ports:
            - "3306"

    medius-server:
        build:
            context: ./medius-server
            dockerfile: Dockerfile
        environment:
            PRODUCTION: 1
        depends_on:
            - medius-db
        networks:
            - medius-network
        ports:
            - "8000:8000"

#    medius-frontend:
#        build:
#            context: ./medius-frontend
#            dockerfile: Dockerfile
#        depends_on:
#            - medius-server
#        networks:
#            - medius-network
#        ports:
#            - "3000:3000"


networks:
  medius-network:
    driver: bridge