version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

# Contain web server and frontend

services:
    medius-server:
        build:
            context: ./medius-server
            dockerfile: Dockerfile
        environment:
            PRODUCTION: 1
            S3_REGION: "${S3_REGION}"
            S3_ENDPOINT: "${S3_ENDPOINT}"
            S3_BUCKET: "${S3_BUCKET}"
            S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
            S3_SECRET_KEY: "${S3_SECRET_KEY}"
        networks:
            - medius-network
        ports:
            - "8000:8000"

    medius-frontend:
        build:
            context: ./medius-frontend
            dockerfile: Dockerfile
            args:
                # - REACT_APP_BASE_API_PATH=http://165.22.106.61:8000/api
                - REACT_APP_BASE_API_PATH=https://medius.tk/api
        environment:
          - "REACT_APP_SC_DISABLE_SPEEDY=true"

        depends_on:
            - medius-server
        networks:
            - medius-network
        ports:
            - "3000:3000"


networks:
  medius-network:
    driver: bridge