version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

# Contain web server and frontend

services:
    medius-server:
        build:
            context: ./medius-server
            dockerfile: Dockerfile
        environment:
            PRODUCTION: 1
        networks:
            - medius-network
        ports:
            - "8000:8000"

    medius-frontend:
        build:
            context: ./medius-frontend
            dockerfile: Dockerfile
        environment:
          - REACT_APP_SC_DISABLE_SPEEDY=true
        depends_on:
            - medius-server
        networks:
            - medius-network
        ports:
            - "3000:3000"


networks:
  medius-network:
    driver: bridge