name: deployment
on:
  push:
    branches:
      - master
      - autodeploy
env:
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
jobs:
  build:
    name: deploy_everything
    runs-on: ubuntu-latest
    steps:
    - name: execute deployment scripts  
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          git clone git@github.com:CaoHoangTung/INT3306-4.git
          cd INT3306-4
          git checkout master
          git pull origin master
          docker-compose up --build -d