name: deployment
on:
  push:
    branches:
      - master
      - autodeploy
jobs:
  build:
    name: deploy_everything
    runs-on: ubuntu-latest
    steps:
    - name: execute deployment scripts  
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          git clone git@github.com:CaoHoangTung/INT3306-4.git
          cd INT3306-4
          git checkout master
          git pull origin master
          export S3_REGION=${{ secrets.S3_REGION }}
          export S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
          export S3_BUCKET=${{ secrets.S3_BUCKET }}
          export S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
          export S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
          echo $S3_REGION
          echo $S3_ENDPOINT
          echo $S3_BUCKET
          echo $S3_ACCESS_KEY
          echo $S3_SECRET_KEY
          docker-compose up --build -d